import { atom } from 'recoil';
import { RawFood, ConsumedRaw } from '@lib/types';

export const isValidState = atom({
  key: 'isValidState',
  default: false,
});

export const searchQueryState = atom<string>({
  key: 'searchQueryState',
  default: '',
});

export const rawFoodsState = atom<RawFood[]>({
  key: 'rawFoodsState',
  default: [
    {
      id: 1,
      name: '닭가슴살',
      description: '신선한 닭가슴살',
      standardAmount: 100,
      kcal: 165,
      carbonHydrate: 0,
      protein: 31,
      fat: 3.6,
      calcium: 0,
      phosphorus: 0,
      vitaminA: 0,
      vitaminD: 0,
      vitaminE: 0,
    },
    {
      id: 2,
      name: '소고기',
      description: '기름기 적은 소고기',
      standardAmount: 100,
      kcal: 250,
      carbonHydrate: 0,
      protein: 26,
      fat: 15,
      calcium: 0,
      phosphorus: 0,
      vitaminA: 0,
      vitaminD: 0,
      vitaminE: 0,
    },
    {
      id: 3,
      name: '연어',
      description: '신선한 연어',
      standardAmount: 100,
      kcal: 208,
      carbonHydrate: 0,
      protein: 20,
      fat: 13,
      calcium: 0,
      phosphorus: 0,
      vitaminA: 0,
      vitaminD: 0,
      vitaminE: 0,
    },
    {
      id: 4,
      name: '오리 가슴살',
      description: '신선한 오리 가슴살',
      standardAmount: 100,
      kcal: 200,
      carbonHydrate: 0,
      protein: 25,
      fat: 10,
      calcium: 0,
      phosphorus: 0,
      vitaminA: 0,
      vitaminD: 0,
      vitaminE: 0,
    },
    {
      id: 5,
      name: '돼지고기',
      description: '기름기 적은 돼지고기',
      standardAmount: 100,
      kcal: 242,
      carbonHydrate: 0,
      protein: 21,
      fat: 17,
      calcium: 0,
      phosphorus: 0,
      vitaminA: 0,
      vitaminD: 0,
      vitaminE: 0,
    },
    {
      id: 6,
      name: '닭다리살',
      description: '신선한 닭다리살',
      standardAmount: 100,
      kcal: 200,
      carbonHydrate: 0,
      protein: 28,
      fat: 8,
      calcium: 0,
      phosphorus: 0,
      vitaminA: 0,
      vitaminD: 0,
      vitaminE: 0,
    },
    {
      id: 7,
      name: '칠면조 가슴살',
      description: '신선한 칠면조 가슴살',
      standardAmount: 100,
      kcal: 189,
      carbonHydrate: 0,
      protein: 29,
      fat: 6,
      calcium: 0,
      phosphorus: 0,
      vitaminA: 0,
      vitaminD: 0,
      vitaminE: 0,
    },
    {
      id: 8,
      name: '방어',
      description: '신선한 방어',
      standardAmount: 100,
      kcal: 230,
      carbonHydrate: 0,
      protein: 22,
      fat: 15,
      calcium: 0,
      phosphorus: 0,
      vitaminA: 0,
      vitaminD: 0,
      vitaminE: 0,
    },
    {
      id: 9,
      name: '돼지 등심',
      description: '기름기 적은 돼지 등심',
      standardAmount: 100,
      kcal: 223,
      carbonHydrate: 0,
      protein: 26,
      fat: 12,
      calcium: 0,
      phosphorus: 0,
      vitaminA: 0,
      vitaminD: 0,
      vitaminE: 0,
    },
    {
      id: 10,
      name: '소고기 안심',
      description: '기름기 적은 소고기 안심',
      standardAmount: 100,
      kcal: 250,
      carbonHydrate: 0,
      protein: 27,
      fat: 14,
      calcium: 0,
      phosphorus: 0,
      vitaminA: 0,
      vitaminD: 0,
      vitaminE: 0,
    },
    {
      id: 11,
      name: '송어',
      description: '신선한 송어',
      standardAmount: 100,
      kcal: 190,
      carbonHydrate: 0,
      protein: 23,
      fat: 10,
      calcium: 0,
      phosphorus: 0,
      vitaminA: 0,
      vitaminD: 0,
      vitaminE: 0,
    },
    {
      id: 12,
      name: '닭 날개',
      description: '신선한 닭 날개',
      standardAmount: 100,
      kcal: 203,
      carbonHydrate: 0,
      protein: 20,
      fat: 13,
      calcium: 0,
      phosphorus: 0,
      vitaminA: 0,
      vitaminD: 0,
      vitaminE: 0,
    },
    {
      id: 13,
      name: '오리고기',
      description: '신선한 오리고기',
      standardAmount: 100,
      kcal: 240,
      carbonHydrate: 0,
      protein: 18,
      fat: 20,
      calcium: 0,
      phosphorus: 0,
      vitaminA: 0,
      vitaminD: 0,
      vitaminE: 0,
    },
    {
      id: 14,
      name: '소갈비',
      description: '기름기 적은 소갈비',
      standardAmount: 100,
      kcal: 260,
      carbonHydrate: 0,
      protein: 24,
      fat: 18,
      calcium: 0,
      phosphorus: 0,
      vitaminA: 0,
      vitaminD: 0,
      vitaminE: 0,
    },
    {
      id: 15,
      name: '닭 안심',
      description: '신선한 닭 안심',
      standardAmount: 100,
      kcal: 150,
      carbonHydrate: 0,
      protein: 32,
      fat: 2,
      calcium: 0,
      phosphorus: 0,
      vitaminA: 0,
      vitaminD: 0,
      vitaminE: 0,
    },
    {
      id: 16,
      name: '돼지 목살',
      description: '기름기 적은 돼지 목살',
      standardAmount: 100,
      kcal: 255,
      carbonHydrate: 0,
      protein: 25,
      fat: 16,
      calcium: 0,
      phosphorus: 0,
      vitaminA: 0,
      vitaminD: 0,
      vitaminE: 0,
    },
    {
      id: 17,
      name: '연어 스테이크',
      description: '신선한 연어 스테이크',
      standardAmount: 100,
      kcal: 220,
      carbonHydrate: 0,
      protein: 21,
      fat: 14,
      calcium: 0,
      phosphorus: 0,
      vitaminA: 0,
      vitaminD: 0,
      vitaminE: 0,
    },
    {
      id: 18,
      name: '소고기 등심',
      description: '기름기 적은 소고기 등심',
      standardAmount: 100,
      kcal: 240,
      carbonHydrate: 0,
      protein: 26,
      fat: 16,
      calcium: 0,
      phosphorus: 0,
      vitaminA: 0,
      vitaminD: 0,
      vitaminE: 0,
    },
    {
      id: 19,
      name: '대구',
      description: '신선한 대구',
      standardAmount: 100,
      kcal: 85,
      carbonHydrate: 0,
      protein: 19,
      fat: 1,
      calcium: 0,
      phosphorus: 0,
      vitaminA: 0,
      vitaminD: 0,
      vitaminE: 0,
    },
    {
      id: 20,
      name: '고등어',
      description: '신선한 고등어',
      standardAmount: 100,
      kcal: 205,
      carbonHydrate: 0,
      protein: 20,
      fat: 13,
      calcium: 0,
      phosphorus: 0,
      vitaminA: 0,
      vitaminD: 0,
      vitaminE: 0,
    },
    {
      id: 21,
      name: '참치',
      description: '신선한 참치',
      standardAmount: 100,
      kcal: 144,
      carbonHydrate: 0,
      protein: 23,
      fat: 5,
      calcium: 0,
      phosphorus: 0,
      vitaminA: 0,
      vitaminD: 0,
      vitaminE: 0,
    },
    {
      id: 22,
      name: '장어',
      description: '신선한 장어',
      standardAmount: 100,
      kcal: 180,
      carbonHydrate: 0,
      protein: 18,
      fat: 12,
      calcium: 0,
      phosphorus: 0,
      vitaminA: 0,
      vitaminD: 0,
      vitaminE: 0,
    },
    {
      id: 23,
      name: '닭고기',
      description: '신선한 닭고기',
      standardAmount: 100,
      kcal: 200,
      carbonHydrate: 0,
      protein: 20,
      fat: 10,
      calcium: 0,
      phosphorus: 0,
      vitaminA: 0,
      vitaminD: 0,
      vitaminE: 0,
    },
    {
      id: 24,
      name: '청어',
      description: '신선한 청어',
      standardAmount: 100,
      kcal: 200,
      carbonHydrate: 0,
      protein: 20,
      fat: 12,
      calcium: 0,
      phosphorus: 0,
      vitaminA: 0,
      vitaminD: 0,
      vitaminE: 0,
    },
    {
      id: 25,
      name: '대하',
      description: '신선한 대하',
      standardAmount: 100,
      kcal: 99,
      carbonHydrate: 0,
      protein: 20,
      fat: 1,
      calcium: 0,
      phosphorus: 0,
      vitaminA: 0,
      vitaminD: 0,
      vitaminE: 0,
    },
    {
      id: 26,
      name: '말고기',
      description: '신선한 말고기',
      standardAmount: 100,
      kcal: 155,
      carbonHydrate: 0,
      protein: 21,
      fat: 8,
      calcium: 0,
      phosphorus: 0,
      vitaminA: 0,
      vitaminD: 0,
      vitaminE: 0,
    },
    {
      id: 27,
      name: '양고기',
      description: '신선한 양고기',
      standardAmount: 100,
      kcal: 294,
      carbonHydrate: 0,
      protein: 25,
      fat: 20,
      calcium: 0,
      phosphorus: 0,
      vitaminA: 0,
      vitaminD: 0,
      vitaminE: 0,
    },
    {
      id: 28,
      name: '붕어',
      description: '신선한 붕어',
      standardAmount: 100,
      kcal: 126,
      carbonHydrate: 0,
      protein: 18,
      fat: 5,
      calcium: 0,
      phosphorus: 0,
      vitaminA: 0,
      vitaminD: 0,
      vitaminE: 0,
    },
    {
      id: 29,
      name: '가자미',
      description: '신선한 가자미',
      standardAmount: 100,
      kcal: 105,
      carbonHydrate: 0,
      protein: 22,
      fat: 1,
      calcium: 0,
      phosphorus: 0,
      vitaminA: 0,
      vitaminD: 0,
      vitaminE: 0,
    },
    {
      id: 30,
      name: '오징어',
      description: '신선한 오징어',
      standardAmount: 100,
      kcal: 92,
      carbonHydrate: 3,
      protein: 16,
      fat: 1,
      calcium: 0,
      phosphorus: 0,
      vitaminA: 0,
      vitaminD: 0,
      vitaminE: 0,
    },
  ],
});

export const consumedRawsState = atom<ConsumedRaw[]>({
    key: 'consumedRawsState',
    default: [
      { petId: 1, rawId: '닭가슴살', serving: 100, date: '2023-07-01' },
      { petId: 1, rawId: '소고기', serving: 150, date: '2023-07-01' },
      { petId: 1, rawId: '연어', serving: 100, date: '2023-07-01' },
      { petId: 1, rawId: '고구마', serving: 100, date: '2023-07-02' },
      { petId: 2, rawId: '오리', serving: 200, date: '2023-07-02' },
      { petId: 2, rawId: '돼지고기', serving: 120, date: '2023-07-02' },
      { petId: 3, rawId: '양고기', serving: 180, date: '2023-07-03' },
      { petId: 3, rawId: '당근', serving: 110, date: '2023-07-03' },
    ],
  });